// InertiaCable - ActionCable setup for Inertia.js
//
// This file is auto-generated by `rails g inertia_cable:install`.
// You can customize the cable URL below if needed.

export { useInertiaCable } from '@inertia-cable/react'
export { InertiaCableProvider } from '@inertia-cable/react'
